# Generated by Django 4.2.3 on 2024-02-08 13:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('personas', '0001_initial'),
        ('usuario', '0001_initial'),
        ('clase', '0001_initial'),
        ('fechaAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActNom', models.CharField(max_length=32, unique=True, verbose_name='actividad')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerNumDoc', models.CharField(max_length=20, unique=True, verbose_name='número de documento de identidad')),
                ('PerApePat', models.CharField(max_length=50, verbose_name='apellido paterno')),
                ('PerApeMat', models.CharField(max_length=50, verbose_name='apellido materno')),
                ('PerNom1', models.CharField(max_length=50, verbose_name='primer nombre')),
                ('PerNom2', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo nombre')),
                ('PerUbi', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Se acepta solamente 6 digitos', regex='^.{6}$')], verbose_name='Ubigeo')),
                ('PerDir', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direccion')),
                ('PerFecNac', models.CharField(blank=True, default=datetime.date.today, max_length=64, null=True, verbose_name='fecha de nacimiento')),
                ('PerTel', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato '+999999'. Se permiten como máximo 15 dígitos.", regex='^\\+?\\d{6,15}$')], verbose_name='número de teléfono')),
                ('DocExp', models.TextField(blank=True, max_length=256, null=True, verbose_name='experiencia')),
                ('DocEsp', models.TextField(blank=True, max_length=256, null=True, verbose_name='especialidad')),
                ('DocCur', models.ManyToManyField(to='curso.curso', verbose_name='cursos')),
                ('PerTipDocId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='personas.tipodocumento', verbose_name='tipo de documento de identidad')),
                ('UsuCod', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Codigo de usuario')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelNum', models.CharField(max_length=32, verbose_name='telefonos')),
                ('DocCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente', verbose_name='docente')),
            ],
            options={
                'verbose_name': 'telefonos',
                'verbose_name_plural': 'telefonos',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpiOpi', models.TextField(max_length=1024, verbose_name='Opinion')),
                ('DocCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente', verbose_name='codigo_docente')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorAla', models.BooleanField(blank=True, default=False, null=True, verbose_name='alarma')),
                ('GraCod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clase.grado', verbose_name='grado')),
                ('NivCod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clase.nivel', verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloHorIni', models.CharField(max_length=32, verbose_name='hora de inicio')),
                ('BloHorFin', models.CharField(max_length=32, verbose_name='hora de fin')),
                ('ActCod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='docente.actividad', verbose_name='actividad')),
                ('CurCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='curso.curso', verbose_name='curso')),
                ('DiaCod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fechaAcademica.dia', verbose_name='dia')),
                ('DocCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='docente.docente', verbose_name='docente')),
                ('HorCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'bloque',
                'verbose_name_plural': 'bloques',
            },
        ),
    ]
