version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./Backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata all_data.json && python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
    ports:
      - "${API_PORT}:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./Backend:/back
  web:
    build:
      context: ./FrontEnd
    command: sh -c "npm run dev"
    environment:
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      NODE_ENV: development
    ports:
      - "${WEB_PORT}:5173"
    restart: always
    depends_on:
      - api
    volumes:
      - ./FrontEnd:/front
      - /front/node_modules

volumes:
  db-data:
  api-data:
  web-data:
