version: "3.8"
services:
  db:
    image: postgres:15
    env_file:
      - reich_pg_properties.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - postgresql_password
  api:
    build:
      context: ./Backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - reich_pg_properties.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    secrets:
      - postgresql_password
  web:
    build:
      context: ./FrontEnd
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - api

volumes:
  db-data:

secrets:
  postgresql_password:
    file: reich_pg_pass