# Generated by Django 4.2.3 on 2024-02-06 12:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerNumDoc', models.CharField(max_length=20, unique=True, verbose_name='número de documento de identidad')),
                ('PerApePat', models.CharField(max_length=50, verbose_name='apellido paterno')),
                ('PerApeMat', models.CharField(max_length=50, verbose_name='apellido materno')),
                ('PerNom1', models.CharField(max_length=50, verbose_name='primer nombre')),
                ('PerNom2', models.CharField(blank=True, max_length=50, null=True, verbose_name='segundo nombre')),
                ('PerUbi', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Se acepta solamente 6 digitos', regex='^.{6}$')], verbose_name='Ubigeo')),
                ('PerDir', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direccion')),
                ('PerFecNac', models.CharField(blank=True, default=datetime.date.today, max_length=64, null=True, verbose_name='fecha de nacimiento')),
                ('PerTel', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato '+999999'. Se permiten como máximo 15 dígitos.", regex='^\\+?\\d{6,15}$')], verbose_name='número de teléfono')),
                ('ApoNivEst', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nivel de estudios')),
                ('ApoCenTra', models.CharField(blank=True, max_length=30, null=True, verbose_name='Centro de trabajo')),
                ('ApoPri', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'apoderado',
                'verbose_name_plural': 'apoderados',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComCom', models.CharField(max_length=256, verbose_name='comentario')),
                ('ComFec', models.CharField(max_length=32, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParPar', models.CharField(max_length=16, verbose_name='parentesco')),
                ('ParApoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoderado.apoderado', verbose_name='apoderado')),
            ],
            options={
                'verbose_name': 'parentesco apoderado-estudiante',
                'verbose_name_plural': 'parentescos apoderados-estudiantes',
            },
        ),
    ]
