# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolNom', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Apoderado', 'Apoderado'), ('Administrador', 'Administrador')], max_length=32, verbose_name='Rol')),
                ('RolDes', models.CharField(max_length=64, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolCod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.rol', verbose_name='Rol')),
                ('UseCod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
