# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoAcaNum', models.IntegerField(default=2000, unique=True, verbose_name='año')),
            ],
            options={
                'verbose_name': 'año academico',
                'verbose_name_plural': 'años academicos',
                'ordering': ['AnoAcaNum'],
            },
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BimNum', models.IntegerField(default=1, verbose_name='bimestre')),
            ],
            options={
                'verbose_name': 'bimestre',
                'verbose_name_plural': 'bimestres',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaNom', models.TextField(max_length=16, verbose_name='dia')),
            ],
            options={
                'verbose_name': 'dia',
                'verbose_name_plural': 'dias',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SemNum', models.IntegerField(default=1, verbose_name='semana')),
            ],
            options={
                'verbose_name': 'semana',
                'verbose_name_plural': 'semanas',
            },
        ),
        migrations.CreateModel(
            name='FechaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fechaAcademica.anoacademico', verbose_name='año')),
                ('BimId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fechaAcademica.bimestre', verbose_name='bimestre')),
                ('SemId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fechaAcademica.semana', verbose_name='semana')),
            ],
            options={
                'verbose_name': 'fecha académica',
                'verbose_name_plural': 'fechas académicas',
            },
        ),
    ]
