# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipDocTip', models.CharField(max_length=16, verbose_name='tipo de documento')),
                ('TipDocDesCor', models.CharField(max_length=64, verbose_name='descripción corta')),
                ('TipDocDesLar', models.CharField(max_length=64, verbose_name='descripción larga')),
            ],
            options={
                'verbose_name': 'tipo de documento de identidad',
                'verbose_name_plural': 'tipos de documento de identidad',
                'ordering': ['TipDocTip'],
            },
        ),
    ]
