# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResNom1', models.CharField(max_length=64, verbose_name='primer nombre')),
                ('ResNom2', models.CharField(blank=True, max_length=64, null=True, verbose_name='segundo nombre')),
                ('ResApePat', models.CharField(max_length=64, verbose_name='primer apellido')),
                ('ResApeMat', models.CharField(max_length=64, verbose_name='segundo apellido')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
    ]
