# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalPar', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota de participacion')),
                ('CalTar', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota de tarea')),
                ('CalExa', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota de examen')),
                ('CalFec', models.CharField(max_length=32, verbose_name='Fecha')),
                ('CurCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
