# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacion', '0001_initial'),
        ('docente', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='DocCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docente.docente', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='EstCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante', verbose_name='Estudiante'),
        ),
    ]
