# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaNom', models.CharField(blank=True, default='Nro. pendiente', max_length=16, null=True, verbose_name='nombre de clase')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GraNum', models.CharField(max_length=32, unique=True, verbose_name='grado')),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
                'ordering': ['GraNum'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NivNom', models.CharField(max_length=32, unique=True, verbose_name='nivel')),
            ],
            options={
                'verbose_name': 'nivel',
                'verbose_name_plural': 'niveles',
                'ordering': ['NivNom'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clase.clase', verbose_name='clase')),
            ],
            options={
                'verbose_name': 'Estudiante_Clase',
                'verbose_name_plural': 'Estudiantes_Clase',
            },
        ),
    ]
