# Generated by Django 4.2.3 on 2024-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('clase', '0001_initial'),
        ('fechaAcademica', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteclase',
            name='EstCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante', verbose_name='estudiante'),
        ),
        migrations.AddField(
            model_name='estudianteclase',
            name='SemCod',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fechaAcademica.semana', verbose_name='semana'),
        ),
        migrations.AddField(
            model_name='clase',
            name='ClaGraCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clase.grado', verbose_name='grado'),
        ),
        migrations.AddField(
            model_name='clase',
            name='ClaNivCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clase.nivel', verbose_name='nivel'),
        ),
        migrations.AddField(
            model_name='clase',
            name='ClaTutCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='docente.docente', verbose_name='docente'),
        ),
        migrations.AlterUniqueTogether(
            name='estudianteclase',
            unique_together={('EstCod', 'ClaCod', 'SemCod')},
        ),
    ]
